### ISSUE TITLE
BNT-4: Keccak-256 and SHA3 Motoko Library

### ISSUE THREAD

**Issue by domwoe** [dfinity/grant-rfps#28]
## Overview

- Status: Open
- Project Type: Traditional: One applicant is selected to work on the task.
- Time Commitment: Days
- Experience Level: Intermediate
- Size: USD 2'000 in ICP (at time of distribution)

## Description

Since the Internet Computer allows canisters to sign Ethereum transactions, there's a need to hash those transactions. This is currently not directly possible in canisters written in Motoko. and a workaround like calling the [EVM utility canister](https://forum.dfinity.org/t/assigned-icdevs-org-bounty-28-evm-utility-canister-6-000/17880) has to be used.

In this bounty, you will implement two cryptographic hashing algorithms in Motoko. Keccak-256 is the hashing algorithm used for signing Ethereum transactions. It is similar to the standardized SHA-3 but uses a different padding. Hence, it makes sense to include both variations, although the official SHA-3 is not used in Ethereum.

## Acceptance Criteria

- Implementation with tests
- [Meaningful readme](https://github.com/dfinity/grant-rfps/blob/main/repo-checklist.md) with usage example 
- Open Source license (e.g. MIT)
- Available in the [mops package manager](https://mops.one/)

## How to apply? 

- Include links to previous relevant work.
- Include a brief overview of how you will complete the task.
- Give an estimated timeline for completing the task.
- Post your application text in [this thread](https://forum.dfinity.org/t/open-dfinity-bounty-4-keccak-256-and-sha3-motoko-library-2000-in-icp/18469)

### SHA-3 and Keccak implementations

- https://github.com/ethereum/eth-hash
- https://github.com/RustCrypto/hashes/tree/master/sha3

### Examples of cryptographic hashing libraries in Motoko
- https://github.com/timohanke/motoko-sha2
- https://github.com/aviate-labs/crypto.mo
- https://github.com/tgalal/motoko-bitcoin

**Comment by domwoe** [comment]
Bounty is already provided by ICDevs: https://forum.dfinity.org/t/open-icdevs-org-bounty-14-big-sha-keccak-4-000/11251/5

**Comment by domwoe** [comment]
Assigned @WenheLI

**Comment by AgCaliva** [comment]
Hi, i know its already assigned, but i wanted to contact you via discord and i cant send you messages without you accepting me as friend.
Hi there, im an experienced programmer but kinda new to smart contracts(i have done very little by using solidity, and solved a bug in harmony chrome wallet). I have not seen the other bounties in detail, but im interested in learning what its needed to do the jobs, since i know more than 15 programming languages. Im currently learning solidity. I can surely do some task.
Do you have some bounty for me who is starting in Motoko? Where i can learn more about the project related topics?
I will be reading the bounties.
Thanks in advance.
I can send you my cv via discord please accept me

**Comment by hanbu97** [comment]
All work has been done:

Here is the repository implemented Sha3 and Keccak in Motoko with plenty of tests.
https://github.com/hanbu97/motoko-sha3

The Library has been published to mops package manager
https://mops.one/sha3

**Comment by hanbu97** [comment]
@domwoe

**Comment by WenheLI** [comment]
@hanbu97 - I am currently traveling. If you have finished, I am ok with assigning this to u.

**Comment by hanbu97** [comment]
@WenheLI Thank you!

**Comment by domwoe** [comment]
Completed by @hanbu97  and @react0r-com. Thank you for your contribution!
